# Generated by Django 5.1.3 on 2024-11-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('Cantidad', models.SmallIntegerField()),
                ('Descripcion', models.CharField(max_length=100)),
                ('Categoria', models.CharField(max_length=20)),
                ('Fech_Cad', models.DateField()),
            ],
        ),
    ]
