# Generated by Django 5.1.3 on 2024-11-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('Membresia', models.CharField(max_length=100)),
                ('Fech_Nac', models.DateField()),
                ('Telefono', models.IntegerField(max_length=12)),
                ('Correo', models.CharField(max_length=100)),
                ('Curp', models.CharField(max_length=100)),
            ],
        ),
    ]
