# Generated by Django 5.1.3 on 2024-11-18 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='costo',
            new_name='Costo',
        ),
    ]
